#!/bin/sh
clear

check_file_exist () {
file=$1
if [ -f $file ]; 
	then echo "The file $file exist..."; 
else 
	echo "The file $file doesn't exist...";
fi
}

if [ $1 != "" ];
        then check_file_exist
else
        echo "Input a filename" && sleep 3
        exit
fi

